// src/Command/themes/auth/vue/app/views/js/components/form/input/input.vue
<script setup>
import { cn } from '@/utils';
import { useVModel } from '@vueuse/core';

const props = defineProps({
    defaultValue: {
        type: [String, Number],
        default: '',
    },
    modelValue: {
        type: [String, Number],
        default: '',
    },
    class: {
        type: String,
        default: '',
    },
});

const emits = defineEmits(['update:modelValue']);

const modelValue = useVModel(props, 'modelValue', emits, {
    passive: true,
    defaultValue: props.defaultValue,
});
</script>

<template>
    <input
        v-model="modelValue"
        :class="
            cn(
                'flex h-10 w-full rounded-md border border-input bg-background px-3 py-2 text-base ring-offset-background file:border-0 file:bg-transparent file:text-sm file:font-medium file:text-foreground placeholder:text-muted-foreground focus-visible:outline-none focus-visible:ring-2 focus-visible:ring-ring focus-visible:ring-offset-2 disabled:cursor-not-allowed disabled:opacity-50 md:text-sm',
                props.class,
            )
        "
    />
</template>

// src/Command/themes/auth/react/app/views/js/components/form/input.jsx
import * as React from "react";

import { cn } from "@/utils";

export default function Input({ className, type, ...props }, ref) {
    return (
        <input
            type={type}
            className={cn(
                "flex h-10 w-full rounded-lg border border-input bg-background px-3 py-2 text-base ring-offset-background file:border-0 file:bg-transparent file:text-sm file:font-medium file:text-foreground placeholder:text-muted-foreground focus-visible:outline-hidden focus-visible:ring-2 focus-visible:ring-ring focus-visible:ring-offset-2 disabled:cursor-not-allowed disabled:opacity-50 md:text-sm",
                className,
            )}
            ref={ref}
            {...props}
        />
    );
}
