// src/Command/themes/auth/vue/app/views/components/form/input/label.vue
<script setup>
import { cn } from '@/utils';
import { Label } from 'radix-vue';
import { computed } from 'vue';

const props = defineProps({
    class: {
        type: String,
        default: '',
    },
});

const delegatedProps = computed(() => {
    const { class: _, ...delegated } = props;
    return delegated;
});
</script>

<template>
    <Label
        v-bind="delegatedProps"
        :class="cn('text-sm font-medium leading-none peer-disabled:cursor-not-allowed peer-disabled:opacity-70', props.class)"
    >
        <slot />
    </Label>
</template>

// src/Command/themes/auth/react/app/views/js/components/form/label.jsx
import * as React from "react";
import { cva } from "class-variance-authority";

import { cn } from "@/utils";

const labelVariants = cva(
    "text-sm font-medium leading-none peer-disabled:cursor-not-allowed peer-disabled:opacity-70",
);

const Label = React.forwardRef(({ className, ...props }, ref) => {
    return (
        <label {...props} ref={ref} className={cn(labelVariants, className)} />
    );
});

Label.displayName = "Label";

export default Label;
