// src/Command/themes/auth/vue/app/views/pages/dashboard.vue
<script setup>
import Layout from '@/layouts/app-layout.vue';
import { Head } from '@inertiajs/vue3';
</script>

<template>
    <Head title="Dashboard" />

    <Layout variant="sidebar" :breadcrumbs="[
        {
            title: 'Dashboard',
            href: '/dashboard',
        },
    ]">
        <div className="py-4 px-4">
            <div className="overflow-hidden shadow-sm sm:rounded-lg bg-black">
                <div className="p-6 text-gray-100">You're logged in!</div>
            </div>
        </div>
    </Layout>
</template>

// src/Command/themes/auth/react/app/views/js/pages/dashboard.jsx
import Layout from "@/layouts/app-layout";
import { Head } from "@inertiajs/react";

export default function Dashboard() {
    return (
        <Layout
            variant="sidebar"
            breadcrumbs={[
                {
                    title: "Dashboard",
                    href: "/dashboard",
                },
            ]}
        >
            <Head title="Dashboard" />

            <div className="py-4 px-4">
                <div className="overflow-hidden shadow-sm sm:rounded-lg bg-black">
                    <div className="p-6 text-gray-100">You're logged in!</div>
                </div>
            </div>
        </Layout>
    );
}
