// src/Command/themes/auth/svelte/app/views/js/pages/dashboard.svelte
<script>
    import Layout from "@/layouts/app-layout.svelte";
</script>

<svelte:head>
  <title>Dashboard</title>
</svelte:head>

<Layout
    breadcrumbs={[
        {
            title: "Dashboard",
            href: "/dashboard",
        },
    ]}
>
    <div class="py-4 px-4">
        <div class="overflow-hidden shadow-sm sm:rounded-lg bg-black">
            <div class="p-6 text-gray-100">You're logged in!</div>
        </div>
    </div>
</Layout>

// src/Command/themes/auth/react/app/views/js/pages/dashboard.jsx
import Layout from "@/layouts/app-layout";
import { Head } from "@inertiajs/react";

export default function Dashboard() {
    return (
        <Layout
            variant="sidebar"
            breadcrumbs={[
                {
                    title: "Dashboard",
                    href: "/dashboard",
                },
            ]}
        >
            <Head title="Dashboard" />

            <div className="py-4 px-4">
                <div className="overflow-hidden shadow-sm sm:rounded-lg bg-black">
                    <div className="p-6 text-gray-100">You're logged in!</div>
                </div>
            </div>
        </Layout>
    );
}
