// src/Command/themes/auth/vue/app/views/components/shared/breadcrumbs/breadcrumbs.vue
<script setup>
import { Link } from '@inertiajs/vue3';
import Breadcrumb from './breadcrumb.vue';
import BreadcrumbList from './breadcrumb-list.vue';
import BreadcrumbItem from './breadcrumb-item.vue';
import BreadcrumbLink from './breadcrumb-link.vue';
import BreadcrumbPage from './breadcrumb-page.vue';
import BreadcrumbSeparator from './breadcrumb-separator.vue';

defineProps({
    breadcrumbs: {
        type: Array,
        required: true,
    },
});
</script>

<template>
    <Breadcrumb>
        <BreadcrumbList>
            <template v-for="(item, index) in breadcrumbs" :key="index">
                <BreadcrumbItem>
                    <template v-if="index === breadcrumbs.length - 1">
                        <BreadcrumbPage>{{ item.title }}</BreadcrumbPage>
                    </template>
                    <template v-else>
                        <BreadcrumbLink>
                            <Link :href="item.href ?? '#'">{{ item.title }}</Link>
                        </BreadcrumbLink>
                    </template>
                </BreadcrumbItem>
                <BreadcrumbSeparator v-if="index !== breadcrumbs.length - 1" />
            </template>
        </BreadcrumbList>
    </Breadcrumb>
</template>

// src/Command/themes/auth/react/app/views/js/components/shared/breadcrumbs.jsx
import {
    Breadcrumb,
    BreadcrumbItem,
    BreadcrumbLink,
    BreadcrumbList,
    BreadcrumbPage,
    BreadcrumbSeparator,
} from "./breadcrumb";
import { Fragment } from "react";

export function Breadcrumbs({ breadcrumbs }) {
    return (
        <>
            {breadcrumbs.length > 0 && (
                <Breadcrumb>
                    <BreadcrumbList>
                        {breadcrumbs.map((item, index) => {
                            const isLast = index === breadcrumbs.length - 1;
                            return (
                                <Fragment key={index}>
                                    <BreadcrumbItem>
                                        {isLast ? (
                                            <BreadcrumbPage>
                                                {item.title}
                                            </BreadcrumbPage>
                                        ) : (
                                            <BreadcrumbLink href={item.href}>
                                                {item.title}
                                            </BreadcrumbLink>
                                        )}
                                    </BreadcrumbItem>
                                    {!isLast && <BreadcrumbSeparator />}
                                </Fragment>
                            );
                        })}
                    </BreadcrumbList>
                </Breadcrumb>
            )}
        </>
    );
}
