// src/Command/themes/auth/svelte/app/views/js/components/shared/heading-small.svelte
<script>
    const { title, description } = $props();
</script>

<template>
    <header>
        <h3 class="mb-0.5 text-base font-medium">{title}</h3>
        {#if description}
            <p class="text-sm text-muted-foreground">
                {description}
            </p>
        {/if}
    </header>
</template>

// src/Command/themes/auth/react/app/views/js/components/shared/heading-small.jsx
export default function HeadingSmall({ title, description }) {
    return (
        <header>
            <h3 className="mb-0.5 text-base font-medium">{title}</h3>
            {description && (
                <p className="text-muted-foreground text-sm">{description}</p>
            )}
        </header>
    );
}
