// src/Command/themes/auth/svelte/app/views/js/components/shared/heading-small.svelte
<script>
    const { title, description } = $props();
</script>

<template>
    <header>
        <h3 class="mb-0.5 text-base font-medium">{title}</h3>
        {#if description}
            <p class="text-sm text-muted-foreground">
                {description}
            </p>
        {/if}
    </header>
</template>

// src/Command/themes/auth/vue/app/views/js/components/shared/heading-small.vue
<script setup>
defineProps({
    title: {
        type: String,
        required: true,
    },
    description: String,
});
</script>

<template>
    <header>
        <h3 class="mb-0.5 text-base font-medium">{{ title }}</h3>
        <p v-if="description" class="text-sm text-muted-foreground">
            {{ description }}
        </p>
    </header>
</template>
