// src/Command/themes/auth/svelte/app/views/js/layouts/app-layout.svelte
<script>
    import Header from "@/components/layout/header.svelte";

    const { breadcrumbs, children } = $props();
</script>

<div
    class="group/sidebar-wrapper flex min-h-svh w-full text-sidebar-foreground has-[[data-variant=inset]]:bg-sidebar flex-col"
    style="--sidebar-width: 16rem; --sidebar-width-icon: 3rem;"
>
    <div>
        <Header />

        {#if breadcrumbs?.length > 1}
            <div class="flex w-full border-b border-sidebar-border/70">
                <div
                    class="mx-auto flex h-12 w-full items-center justify-start px-4 text-neutral-500 md:max-w-7xl"
                >
                    <nav aria-label="breadcrumb" class="">
                        <ol
                            class="flex flex-wrap items-center gap-1.5 break-words text-sm text-muted-foreground sm:gap-2.5"
                        >
                            {#each breadcrumbs as breadcrumb, i}
                                {#if i === breadcrumbs.length - 1}
                                    <li
                                        class="inline-flex items-center gap-1.5"
                                    >
                                        <span
                                            role="link"
                                            aria-disabled="true"
                                            aria-current="page"
                                            class="font-normal text-foreground"
                                            >Dashboard</span
                                        >
                                    </li>
                                {:else}
                                    <li
                                        class="inline-flex items-center gap-1.5"
                                    >
                                        <a
                                            href="/dashboard"
                                            class="transition-colors hover:text-foreground"
                                            >Dashboard</a
                                        >
                                    </li>
                                {/if}

                                {#if i < breadcrumbs.length - 1}
                                    <li
                                        role="presentation"
                                        aria-hidden="true"
                                        class="[&amp;>svg]:h-3.5 [&amp;>svg]:w-3.5"
                                    >
                                        <svg
                                            xmlns="http://www.w3.org/2000/svg"
                                            width="24"
                                            height="24"
                                            viewBox="0 0 24 24"
                                            fill="none"
                                            stroke="currentColor"
                                            stroke-width="2"
                                            stroke-linecap="round"
                                            stroke-linejoin="round"
                                            class="lucide lucide-chevron-right-icon"
                                            ><path d="m9 18 6-6-6-6"
                                            ></path></svg
                                        >
                                    </li>
                                {/if}
                            {/each}
                        </ol>
                    </nav>
                </div>
            </div>
        {/if}
    </div>

    <main
        class="mx-auto flex h-full w-full max-w-7xl flex-1 flex-col gap-4 rounded-xl"
    >
        {@render children()}
    </main>
</div>

// src/Command/themes/auth/react/app/views/js/layouts/app-layout.jsx
import { useState } from "react";
import { Breadcrumbs } from "@/components/shared/breadcrumbs";
import {
    SidebarProvider,
    SidebarInset,
    SidebarTrigger,
} from "../components/layout/sidebar";
import { AppHeader } from "../components/layout/header";

export default function AppLayout({
    children,
    breadcrumbs,
    variant = "sidebar",
    ...props
}) {
    const [isOpen, setIsOpen] = useState(() =>
        typeof window !== "undefined"
            ? localStorage.getItem("sidebar") !== "false"
            : true,
    );

    const handleSidebarChange = (open) => {
        setIsOpen(open);

        if (typeof window !== "undefined") {
            localStorage.setItem("sidebar", String(open));
        }
    };

    if (variant === "header") {
        return (
            <div className="flex min-h-screen w-full flex-col">
                <AppHeader breadcrumbs={breadcrumbs} />
                <main
                    className="mx-auto flex h-full w-full max-w-7xl flex-1 flex-col gap-4 rounded-xl"
                    {...props}
                >
                    {children}
                </main>
            </div>
        );
    }

    return (
        <SidebarProvider
            defaultOpen={isOpen}
            open={isOpen}
            onOpenChange={handleSidebarChange}
        >
            <AppHeader variant="sidebar" breadcrumbs={breadcrumbs} />
            <SidebarInset variant="sidebar" {...props}>
                <header className="border-sidebar-border/50 flex h-16 shrink-0 items-center gap-2 border-b px-6 transition-[width,height] ease-linear group-has-data-[collapsible=icon]/sidebar-wrapper:h-12 md:px-4">
                    <div className="flex items-center gap-2">
                        <SidebarTrigger className="-ml-1 [&_svg]:pointer-events-none [&_svg]:size-4 [&_svg]:shrink-0" />
                        <Breadcrumbs breadcrumbs={breadcrumbs} />
                    </div>
                </header>

                {children}
            </SidebarInset>
        </SidebarProvider>
    );
}
