// src/Command/themes/auth/react/app/views/js/components/form/label.jsx
import * as React from "react";
import { cva } from "class-variance-authority";

import { cn } from "@/utils";

const labelVariants = cva(
    "text-sm font-medium leading-none peer-disabled:cursor-not-allowed peer-disabled:opacity-70",
);

const Label = React.forwardRef(({ className, ...props }, ref) => {
    return (
        <label {...props} ref={ref} className={cn(labelVariants, className)} />
    );
});

Label.displayName = "Label";

export default Label;

// src/Command/themes/auth/svelte/app/views/js/components/form/label.svelte
<script>
import { cn } from "@/utils";
import { cva } from "class-variance-authority";

const { class: className, children, ...props } = $props();

    const labelVariants = cva(
        "text-sm font-medium leading-none peer-disabled:cursor-not-allowed peer-disabled:opacity-70",
    );
</script>

<label {...props} class={cn(labelVariants, className)}>
    {@render children()}
</label>
